version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: defect_user
      POSTGRES_PASSWORD: defect_password
      POSTGRES_DB: defect_management
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - defect_network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - defect_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://defect_user:defect_password@db:5432/defect_management
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    networks:
      - defect_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - defect_network

volumes:
  postgres_data:

networks:
  defect_network:
    driver: bridge
